apiVersion: v1
kind: Service
metadata:
  name: enterprise-devops-app-service
  labels:
    app: enterprise-devops-app
spec:
  type: ClusterIP
  selector:
    app: enterprise-devops-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
