apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enterprise-devops-app-pdb
  namespace: default
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      app: enterprise-devops-app
