# Project 3.4 · Task 4 — ArgoCD Application (GitOps).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-app
  namespace: argocd          
spec:
  project: employee-app
  source:
    repoURL: https://github.com/LikithKumar0112/k8-capstone-project.git
    targetRevision: main
    path: k8s                
  destination:
    server: https://kubernetes.default.svc
    namespace: employee-app
  syncPolicy:
    automated:
      prune: true            
      selfHeal: true         
    syncOptions:
      - CreateNamespace=true
      
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: backend
      namespace: employee-app
      jsonPointers:
        - /spec/replicas
