apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: employee-app
  namespace: argocd
spec:
  description: Employee Management capstone
  sourceRepos:
    - https://github.com/LikithKumar0112/k8-capstone-project.git
  destinations:
    - namespace: employee-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
