#Backend (Spring Boot)
backend:
  image:
    repository: likith0129/employee-backend
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicas: 2
  port: 8082
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60

# Frontend (React + nginx)
frontend:
  image:
    repository: likith0129/employee-frontend
    tag: "1.0.1"
    pullPolicy: IfNotPresent
  replicas: 2
  service:
    type: LoadBalancer        
    port: 80
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# MySQL (StatefulSet + persistent storage)
mysql:
  image: mysql:8.0
  storage: 5Gi
  storageClassName: ""        
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

#Redis (cache)
redis:
  image: redis:7-alpine
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Non-secret config (ConfigMap)
config:
  datasourceUrl: jdbc:mysql://mysql:3306/employeedb
  redisHost: redis
  redisPort: "6379"
  corsAllowedOrigins: "*"

# Secrets (DUMMY values for the capstone - override in real use)
secret:
  datasourceUsername: employee
  datasourcePassword: "SET_VIA_SEALED_SECRET"
  mysqlRootPassword: "SET_VIA_SEALED_SECRET"
  mysqlDatabase: employeedb
  mysqlUser: employee
  mysqlPassword: "SET_VIA_SEALED_SECRET"

# Ingress (optional; alternative to the LoadBalancer service) 
ingress:
  enabled: false
  host: employee.example.com
